price:
 #Use your standard API key from finnhub.io 
 Finnhub_API-Key: 

 #Enter in the stock symbol, each one followed by a comma. Does not support crypto
 Stocks: 
  -APPl
  -TSLA
  -ETH-USD
  -FBGRX

 #By default, the free plan is selected. If you have the all-in-one plan, change it to 1
 Plan: 0
 
 #Enter in the file path for the stock csv file. By default, the 
 Path: stocks.csv
